### ISSUE TITLE
App pointing to address 0x00 instead of user input in From field

### ISSUE THREAD

**Issue by plasmacorral** [svanas/migratooor#3]
I noticed that the UI displays assets that are NOT associated with the address as input according to etherscan.  
<img width="1391" alt="Screen Shot 2022-01-27 at 9 44 22 AM" src="https://user-images.githubusercontent.com/32695229/151408639-fc32ef36-3079-4ca4-a6b0-db121248f7ad.png">

![Screen Shot 2022-01-27 at 12 10 54 PM](https://user-images.githubusercontent.com/32695229/151408708-9a556bb6-62bb-43c2-9586-cc8ee84f105f.png)

When I select the assets and try to migrate, I get a message about transferring assets from 0x00...rather than the address I input.  Then I am prompted for the private key for 0x00 and am unable to complete any transfer

![Screen Shot 2022-01-27 at 12 11 51 PM](https://user-images.githubusercontent.com/32695229/151408862-39e56ee8-4de8-4b07-9458-746fae60bb9d.png)

![Screen Shot 2022-01-27 at 12 14 24 PM](https://user-images.githubusercontent.com/32695229/151409304-6e5eadd5-9bb5-42e0-9ad8-1947967d75af.png)

**Comment by svanas** [comment]
Fixed in https://github.com/svanas/delphereum/commit/342c712ff6f92cd85bedd6251fb658ee9dbe666e
